import { ArrowDownLeft, Check, Mail, ScanSearch } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import type { Account, FinanceState } from "@/lib/localDb";
import { useState } from "react";

export interface MockEmailCandidate { id: string; merchant: string; amount: number; date: string; bank: string; category: string; accountId: string; }
const candidates = (accounts: Account[]): MockEmailCandidate[] => { const account = accounts.find((item) => item.type === "debit") ?? accounts[0]; return [{ id: "mock-qris-1", merchant: "Kopi Kenangan Senayan", amount: 58000, date: new Date().toISOString().slice(0, 10), bank: account?.brand ?? "BCA", category: "Food", accountId: account?.id ?? "" }, { id: "mock-qris-2", merchant: "Transjakarta QRIS", amount: 20000, date: new Date().toISOString().slice(0, 10), bank: account?.brand ?? "BCA", category: "Transport", accountId: account?.id ?? "" }]; };

export function GmailMockImporter({ state, onImport }: { state: FinanceState; onImport: (items: MockEmailCandidate[]) => void }) {
  const [scanned, setScanned] = useState(false);
  const [selected, setSelected] = useState<string[]>([]);
  const items = candidates(state.accounts);
  const toggle = (itemId: string) => setSelected((current) => current.includes(itemId) ? current.filter((id) => id !== itemId) : [...current, itemId]);
  return <section className="mt-6 rounded-2xl border border-amber-400/20 bg-amber-400/5 p-5 sm:p-6" data-testid="gmail-mock-importer"><div className="mb-4 flex flex-wrap items-start justify-between gap-3"><div className="flex items-start gap-3"><div className="grid size-10 place-items-center rounded-xl bg-amber-500/12 text-amber-400"><Mail size={18} /></div><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-amber-400">QRIS inbox importer</p><h2 className="font-heading text-xl font-bold">Preview normalized emails</h2><p className="mt-1 text-xs text-muted-foreground">Gmail OAuth is <strong className="text-amber-400">MOCKED</strong>; only structured fields will be retained later.</p></div></div><Badge variant="outline" className="border-amber-400/30 text-amber-400">MOCKED DATA</Badge></div>{!scanned ? <Button data-testid="gmail-mock-scan-button" onClick={() => { setScanned(true); setSelected(items.map((item) => item.id)); }} variant="outline" className="gap-2 border-amber-400/30 text-amber-300"><ScanSearch size={15} /> Scan sample QRIS emails</Button> : <div className="space-y-3">{items.map((item) => <label key={item.id} className="flex cursor-pointer items-center gap-3 rounded-xl border border-border/60 bg-background/35 p-3 hover:bg-background/60"><input data-testid={`gmail-mock-select-${item.id}`} type="checkbox" checked={selected.includes(item.id)} onChange={() => toggle(item.id)} className="size-4 accent-primary" /><div className="grid size-9 place-items-center rounded-lg bg-rose-500/12 text-rose-400"><ArrowDownLeft size={16} /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{item.merchant}</p><p className="text-[11px] text-muted-foreground">{item.bank} · {item.category} · {item.date}</p></div><p className="font-data text-xs font-bold">−Rp{item.amount.toLocaleString("id-ID")}</p></label>)}<Button data-testid="gmail-mock-import-button" disabled={!selected.length} onClick={() => onImport(items.filter((item) => selected.includes(item.id)))} className="gap-2"><Check size={15} /> Import {selected.length} normalized transaction</Button></div>}</section>;
}