import { CalendarClock, Download, FileText, MailCheck } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import type { FinanceState } from "@/lib/localDb";

const money = (value: number, state: FinanceState) => new Intl.NumberFormat(state.locale === "id" ? "id-ID" : "en-US", { style: "currency", currency: state.baseCurrency, maximumFractionDigits: state.baseCurrency === "IDR" ? 0 : 2, notation: value > 1000000 ? "compact" : "standard" }).format(value / (state.exchangeRates[state.baseCurrency] || 1));

export function ReportCenter({ state, currentMonth, onPrint }: { state: FinanceState; currentMonth: string; onPrint: () => void }) {
  const items = state.transactions.filter((item) => item.date.slice(0, 7) === currentMonth); const expense = items.filter((item) => item.kind === "expense").reduce((sum, item) => sum + item.baseAmount, 0); const income = items.filter((item) => item.kind === "income").reduce((sum, item) => sum + item.baseAmount, 0); const today = new Date().toISOString().slice(0, 10); const todayItems = items.filter((item) => item.date === today); const todayExpense = todayItems.filter((item) => item.kind === "expense").reduce((sum, item) => sum + item.baseAmount, 0); const todayIncome = todayItems.filter((item) => item.kind === "income").reduce((sum, item) => sum + item.baseAmount, 0);
  const categories = Array.from(new Set(items.filter((item) => item.kind === "expense").map((item) => item.category))).map((category) => ({ category, total: items.filter((item) => item.kind === "expense" && item.category === category).reduce((sum, item) => sum + item.baseAmount, 0) })).sort((a, b) => b.total - a.total).slice(0, 3);
  return <section className="mt-6 rounded-2xl border border-border/70 bg-card/75 p-5 shadow-sm sm:p-6" data-testid="report-center"><div className="mb-5 flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div className="flex items-start gap-3"><div className="grid size-10 place-items-center rounded-xl bg-indigo-500/12 text-indigo-400"><FileText size={18} /></div><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-indigo-400">Esplant report center</p><h2 className="font-heading text-xl font-bold">Daily summary preview</h2><p className="mt-1 text-xs text-muted-foreground">Ringkas, informatif, dan memakai angka dashboard yang sama.</p></div></div><div className="flex gap-2"><Badge variant="secondary" className="gap-1"><CalendarClock size={12} /> Daily default</Badge><Button data-testid="report-pdf-button" onClick={onPrint} className="gap-2"><Download size={15} /> Download PDF</Button></div></div><div data-testid="report-print-surface" className="rounded-xl border border-border/60 bg-background/45 p-5"><div className="flex items-start justify-between gap-4 border-b border-border/60 pb-4"><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-primary">Esplant · Financial Tracker</p><h3 className="mt-1 font-heading text-xl font-bold">Daily financial summary</h3><p className="mt-1 text-xs text-muted-foreground">{today} · {state.profileName}</p></div><Badge className="gap-1"><MailCheck size={11} /> Email ready</Badge></div><div className="mt-5 grid gap-3 sm:grid-cols-4"><Metric label="Today spending" value={money(todayExpense, state)} tone="rose" /><Metric label="Today income" value={money(todayIncome, state)} tone="green" /><Metric label="Month expense" value={money(expense, state)} /><Metric label="Month net flow" value={money(income - expense, state)} /></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><div><p className="mb-2 text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Top categories</p>{categories.map((item) => <div key={item.category} className="flex justify-between border-b border-border/40 py-1.5 text-xs"><span>{item.category}</span><span className="font-data">{money(item.total, state)}</span></div>)}</div><div><p className="mb-2 text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Five recent transactions</p>{items.slice(0, 5).map((item) => <div key={item.id} className="flex justify-between border-b border-border/40 py-1.5 text-xs"><span className="truncate pr-3">{item.description}</span><span className="font-data">{money(item.baseAmount, state)}</span></div>)}</div></div></div><p className="mt-3 flex items-center gap-2 text-[10px] text-muted-foreground"><MailCheck size={13} className="text-primary" /> Resend delivery configured · use Send daily report below for PDF email</p></section>;
}

function Metric({ label, value, tone }: { label: string; value: string; tone?: "rose" | "green" }) { return <div><p className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">{label}</p><p className={`mt-1 font-data text-lg font-bold ${tone === "rose" ? "text-rose-400" : tone === "green" ? "text-emerald-400" : ""}`}>{value}</p></div>; }