import { useRef } from "react";
import { Bell, Download, FileText, Moon, Settings2, Sun, Trash2, Upload } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import type { FinanceState } from "@/lib/localDb";

export function SettingsPanel({ state, profileDraft, setProfileDraft, updateState, onSaveProfile, onCsv, onJson, onImport, onErase, onPrint, onReminder }: { state: FinanceState; profileDraft: string; setProfileDraft: (value: string) => void; updateState: (updates: Partial<FinanceState>) => void; onSaveProfile: () => void; onCsv: () => void; onJson: () => void; onImport: (file: File) => void; onErase: () => void; onPrint: () => void; onReminder: () => void }) {
  const isId = state.locale === "id";
  const fileRef = useRef<HTMLInputElement>(null);
  return <div className="animate-rise-in"><div className="mb-6"><p className="mb-2 text-[10px] font-bold uppercase tracking-[0.22em] text-primary">Control room / settings</p><h1 className="font-heading text-3xl font-extrabold tracking-tight sm:text-4xl">{isId ? "Pengaturan Esplant" : "Esplant Settings"}</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">{isId ? "Preferensi penting saja: profil, tampilan, backup, dan jadwal lokal." : "Only the essentials: profile, appearance, backup, and local schedule."}</p></div><div className="grid gap-6 xl:grid-cols-2">
    <Card className="border-border/70 bg-card/75 p-5 sm:p-6"><div className="mb-5 flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-primary/12 text-primary"><Settings2 size={18} /></div><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-muted-foreground">Local profile</p><h2 className="font-heading text-xl font-bold">{isId ? "Profil & tampilan" : "Profile & appearance"}</h2></div></div><label className="block"><span className="mb-2 block text-xs font-semibold text-muted-foreground">{isId ? "Nama panggilan" : "Nickname"}</span><div className="flex gap-2"><input data-testid="profile-name-input" value={profileDraft} onChange={(event) => setProfileDraft(event.target.value)} placeholder={isId ? "Nama kamu" : "Your name"} className="h-10 min-w-0 flex-1 rounded-lg border border-border bg-background px-3 text-sm outline-none focus:border-primary" /><Button data-testid="profile-save-button" onClick={onSaveProfile} size="sm">{isId ? "Simpan" : "Save"}</Button></div></label><div className="mt-5 grid gap-4 sm:grid-cols-2"><div><p className="mb-2 text-xs font-semibold text-muted-foreground">{isId ? "Bahasa" : "Language"}</p><div className="grid grid-cols-2 gap-2"><button type="button" data-testid="language-id-button" onClick={() => updateState({ locale: "id" })} className={`rounded-lg border px-3 py-2 text-xs font-bold ${state.locale === "id" ? "border-primary bg-primary/10 text-primary" : "border-border text-muted-foreground"}`}>Bahasa</button><button type="button" data-testid="language-en-button" onClick={() => updateState({ locale: "en" })} className={`rounded-lg border px-3 py-2 text-xs font-bold ${state.locale === "en" ? "border-primary bg-primary/10 text-primary" : "border-border text-muted-foreground"}`}>English</button></div></div><div><p className="mb-2 text-xs font-semibold text-muted-foreground">{isId ? "Tampilan" : "Appearance"}</p><div className="grid grid-cols-2 gap-2"><button type="button" data-testid="settings-dark-mode-button" onClick={() => updateState({ theme: "dark" })} className={`flex items-center justify-center gap-1.5 rounded-lg border px-3 py-2 text-xs font-bold ${state.theme === "dark" ? "border-primary bg-primary/10 text-primary" : "border-border text-muted-foreground"}`}><Moon size={13} />Dark</button><button type="button" data-testid="settings-light-mode-button" onClick={() => updateState({ theme: "light" })} className={`flex items-center justify-center gap-1.5 rounded-lg border px-3 py-2 text-xs font-bold ${state.theme === "light" ? "border-primary bg-primary/10 text-primary" : "border-border text-muted-foreground"}`}><Sun size={13} />Light</button></div></div></div></Card>
    <div className="space-y-6">
      <Card className="border-border/70 bg-card/75 p-5 sm:p-6"><div className="mb-4"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-muted-foreground">Backup & export</p><h2 className="mt-1 font-heading text-xl font-bold">{isId ? "Bawa datamu ke mana saja" : "Take your data anywhere"}</h2></div><div className="grid gap-2 sm:grid-cols-3"><Button data-testid="export-csv-button" variant="outline" onClick={onCsv} className="gap-2"><FileText size={15} />CSV</Button><Button data-testid="export-json-button" variant="outline" onClick={onJson} className="gap-2"><Download size={15} />JSON</Button><Button data-testid="print-pdf-button" variant="outline" onClick={onPrint} className="gap-2"><FileText size={15} />PDF</Button></div><div className="mt-3 flex flex-wrap items-center gap-2"><input ref={fileRef} data-testid="import-json-input" type="file" accept="application/json,.json" className="hidden" onChange={(event) => { const file = event.target.files?.[0]; if (file) onImport(file); event.target.value = ""; }} /><Button data-testid="import-json-button" variant="outline" onClick={() => fileRef.current?.click()} className="gap-2 border-primary/40 text-primary hover:bg-primary/8"><Upload size={15} />{isId ? "Impor JSON" : "Import JSON"}</Button><button type="button" data-testid="erase-all-button" onClick={onErase} className="flex items-center gap-1.5 rounded-lg border border-red-500/30 px-3 py-2 text-xs font-bold text-red-400 hover:bg-red-500/8"><Trash2 size={13} />{isId ? "Hapus semua data" : "Erase all data"}</button></div><p className="mt-3 text-[10px] leading-relaxed text-muted-foreground">{isId ? "Impor menerima file backup JSON Esplant. Semua proses terjadi di browser — tidak ada data yang diunggah ke server." : "Import accepts an Esplant JSON backup. Everything happens in the browser — nothing is uploaded to a server."}</p></Card>
      <Card className="border-border/70 bg-card/75 p-5 sm:p-6"><div className="mb-4 flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-primary/12 text-primary"><Bell size={18} /></div><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-muted-foreground">Local scheduler</p><h2 className="font-heading text-xl font-bold">{isId ? "Pengingat laporan" : "Report reminders"}</h2></div></div><div className="grid gap-3 sm:grid-cols-2"><input data-testid="schedule-email-input" type="email" placeholder={isId ? "Email tujuan laporan" : "Report recipient email"} value={state.schedule.email} onChange={(event) => updateState({ schedule: { ...state.schedule, email: event.target.value } })} className="h-10 rounded-lg border border-border bg-background px-3 text-sm outline-none focus:border-primary" /><select data-testid="schedule-frequency-select" value={state.schedule.frequency} onChange={(event) => updateState({ schedule: { ...state.schedule, frequency: event.target.value as FinanceState["schedule"]["frequency"] } })} className="h-10 rounded-lg border border-border bg-background px-3 text-xs font-semibold"><option value="daily">{isId ? "Harian" : "Daily"}</option><option value="weekly">{isId ? "Mingguan" : "Weekly"}</option><option value="monthly">{isId ? "Bulanan" : "Monthly"}</option></select></div><div className="mt-3 flex gap-2"><button type="button" data-testid="browser-reminder-button" onClick={onReminder} className="rounded-lg border border-primary/30 px-3 py-2 text-xs font-bold text-primary hover:bg-primary/8">{isId ? "Aktifkan pengingat browser" : "Enable browser reminder"}</button><button type="button" data-testid="schedule-toggle-button" onClick={() => updateState({ schedule: { ...state.schedule, enabled: !state.schedule.enabled } })} className={`rounded-lg px-3 py-2 text-xs font-bold ${state.schedule.enabled ? "bg-primary text-primary-foreground" : "border border-border text-muted-foreground"}`}>{state.schedule.enabled ? (isId ? "Aktif" : "Enabled") : (isId ? "Nonaktif" : "Disabled")}</button></div><p className="mt-3 text-[10px] text-muted-foreground">{isId ? "Email di atas dipakai sebagai tujuan default tombol kirim laporan. Maksimum 3 email per hari untuk mencegah spam." : "The email above is used as the default recipient for report sending. Maximum 3 emails per day to prevent spam."}</p></Card>
    </div>
  </div></div>;
}
